package com.consacresdeleternel.consacrebeamer.consts;

import java.util.Arrays;
import java.util.List;

public class BibelConsts {
	public static List<String> BIBEL_BOOK_NAMES_DE = Arrays.asList(
			"1 Mose",
			"2 Mose",
			"3 Mose",
			"4 Mose",
			"5 Mose",
			"Josua",
			"Richter",
			"Rut",
			"1 Samuel",
			"2 Samuel",
			"1 Könige",
			"2 Könige",
			"1 Chronik",
			"2 Chronik",
			"Esra",
			"Nehemia",
			"Ester",
			"Job",
			"Psalmen",
			"Sprüche",
			"Prediger",
			"Hoheslied",
			"Jesaja",
			"Jeremia",
			"Klagelieder Jeremias",
			"Ezechiel",
			"Daniel",
			"Hosea",
			"Joel",
			"Amos",
			"Obadja",
			"Jona",
			"Micha",
			"Nahum",
			"Habakuk",
			"Zefanja",
			"Haggai",
			"Sacharja",
			"Maleachi",
			"Matthäus",
			"Markus",
			"Lukas",
			"Johannes",
			"Apostelgeschichte",
			"Römer",
			"1. Korinther",
			"2. Korinther",
			"Galater",
			"Epheser",
			"Philipper",
			"Kolosser",
			"1 Thessalonicher",
			"2 Thessalonicher",
			"1 Timotheus",
			"2 Timotheus",
			"Titus",
			"Philemon",
			"Hebräer",
			"Jakobus",
			"1 Petrus",
			"2 Petrus",
			"1 Johannes",
			"2 Johannes",
			"3 Johannes",
			"Judas",
			"Offenbarung");
	
	public static List<String> BIBEL_BOOK_NAMES_FR = Arrays.asList(
			"Genèse",
			"Exode",
			"Levitique",
			"Nombres",
			"Deuteronome",
			"Josué",
			"Juges",
			"Ruth",
			"1 Samuel",
			"2 Samuel",
			"1 Rois",
			"2 Rois",
			"1 Chroniques",
			"2 Chroniques",
			"Esdras",
			"Nehemi",
			"Esther",
			"Job",
			"Psaumes",
			"Proverbes",
			"Ecclesiastes",
			"Cantiques des cantiques",
			"Isaie",
			"Jeremie",
			"Lamentations",
			"Ezekiel",
			"Daniel",
			"Osée",
			"Joel",
			"Amos",
			"Abadias",
			"Jonas",
			"Miché",
			"Nahum",
			"Habaquq",
			"Sophonie",
			"Aggée",
			"Zacharie",
			"Malachie",
			"Matthieu",
			"Marc",
			"Luc",
			"Jean",
			"Actes des apotres",
			"Romains",
			"1 Corinthiens",
			"2 Corinthiens",
			"Galates",
			"Ephésiens",
			"Philippeans",
			"Colossiens",
			"1 Théssaloniciens",
			"2 Théssaloniciens",
			"1 Timothée",
			"2 Timothée",
			"Tite",
			"Philémon",
			"Hébreux",
			"James",
			"1 Pierre",
			"2 Pierre",
			"1 Jean",
			"2 Jean",
			"3 Jean",
			"Jude",
			"Apocalypse");
	
	public static List<String> BIBEL_BOOK_NAMES_EN = Arrays.asList(
			"Geneseis",
			"Exodus",
			"Leviticus",
			"Numbers",
			"Deuteronomy",
			"Joshua",
			"Judges",
			"Ruth",
			"1 Samuel",
			"2 Samuel",
			"1 Kings",
			"2 Kings",
			"1 chronicles",
			"2 Chronicles",
			"Ezra",
			"Nehemiah",
			"Esther",
			"Job",
			"Psalms",
			"Proverbs",
			"Ecclesiastes",
			"Songofsolomon",
			"Isaiah",
			"Jeremiah",
			"Lamentations",
			"Ezekiel",
			"Daniel",
			"Hosea",
			"Joel",
			"Amos",
			"Obadiah",
			"Jonah",
			"Micah",
			"Nahum",
			"Habakkuk",
			"Zephaniah",
			"Haggai",
			"Zachariah",
			"Malachi",
			"Matthew",
			"Mark",
			"Luke",
			"John",
			"Acts",
			"Romans",
			"1 Corinthians",
			"2 Corinthians",
			"Galatians",
			"Ephesians",
			"Philippians",
			"Colossians",
			"1 Thessalonians",
			"2 Thessalonians",
			"1 Timothy",
			"2 Timothy",
			"Titus",
			"Philemon",
			"Hebrews",
			"James",
			"1 Peter",
			"2 Peter",
			"1 John",
			"2 John",
			"3 John",
			"Jude",
			"Revelation");
}
